export const COMPANY_NAMES = {
  AAPL: "Apple", MSFT: "Microsoft", NVDA: "Nvidia", AMD: "AMD", V: "Visa",
  AVGO: "Broadcom", CRM: "Salesforce", ORCL: "Oracle", ADBE: "Adobe", NOW: "ServiceNow", QCOM: "Qualcomm",
  JNJ: "J&J", PFE: "Pfizer", UNH: "UnitedHealth", MRNA: "Moderna", LLY: "Eli Lilly",
  ISRG: "Intuitive Surgical", TMO: "Thermo Fisher",
  EOG: "EOG Resources", CVX: "Chevron", HAL: "Halliburton", COP: "ConocoPhillips", OXY: "Occidental",
  CAT: "Caterpillar", BA: "Boeing", GE: "GE", HON: "Honeywell", DE: "Deere",
  ETN: "Eaton", PWR: "Quanta Services", TT: "Trane Technologies",
  JPM: "JPMorgan", BAC: "Bank of America", GS: "Goldman", BLK: "BlackRock", MS: "Morgan Stanley",
  TSLA: "Tesla", NKE: "Nike", MCD: "McDonald's", HD: "Home Depot", BKNG: "Booking Holdings",
  PG: "Procter & Gamble", KO: "Coca-Cola", PEP: "PepsiCo", WMT: "Walmart", COST: "Costco",
  GOOGL: "Alphabet", META: "Meta", NFLX: "Netflix", DIS: "Disney", SPOT: "Spotify",
  DUK: "Duke Energy", SO: "Southern Co", AEP: "AEP", EXC: "Exelon", NEE: "NextEra",
  LIN: "Linde", APD: "Air Products", NEM: "Newmont", FCX: "Freeport", SHW: "Sherwin-Williams",
  PLD: "Prologis", AMT: "American Tower", EQIX: "Equinix", SPG: "Simon Property", WELL: "Welltower",
  DLR: "Digital Realty", O: "Realty Income", VTR: "Ventas", PSA: "Public Storage",
  ASML: "ASML", AMAT: "Appl. Materials", LRCX: "Lam Research", KLAC: "KLA Corp", MU: "Micron",
  LMT: "Lockheed Martin", RTX: "RTX", NOC: "Northrop Grumman", GD: "General Dynamics", HII: "HII",
  AXON: "Axon Enterprise", HWM: "Howmet Aerospace",
  DHI: "D.R. Horton", LEN: "Lennar", PHM: "PulteGroup", TOL: "Toll Brothers", NVR: "NVR",
  UNP: "Union Pacific", CSX: "CSX", FDX: "FedEx", UPS: "UPS", JBHT: "J.B. Hunt",
  ANET: "Arista Networks",
};
